# Generated by Django 5.2.1 on 2025-05-17 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Luminova', '0001_initial'),
        ('auth', '0014_delete_roldescripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del rol')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_extendida', to='auth.group')),
            ],
        ),
    ]
