# Generated by Django 5.2.1 on 2025-05-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Luminova', '0002_auditoriaacceso_categoriainsumo_cliente_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias_productos/')),
            ],
            options={
                'verbose_name': 'Categoría de Producto Terminado',
                'verbose_name_plural': 'Categorías de Productos Terminados',
            },
        ),
        migrations.AddField(
            model_name='categoriainsumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias_insumos/'),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_terminados/'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='insumos/'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Luminova.categoriaproductoterminado'),
        ),
    ]
