# Generated by Django 5.2.1 on 2025-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Luminova', '0004_cliente_detalleorden_factura_insumo_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='insumos'),
        ),
    ]
