# Generated by Django 5.2.1 on 2025-05-21 20:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Luminova', '0005_alter_insumo_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Insumo',
                'verbose_name_plural': 'Categorías de Insumos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auditoriaacceso',
            options={'ordering': ['-fecha_acceso'], 'verbose_name': 'Auditoría de Acceso', 'verbose_name_plural': 'Auditorías de Acceso'},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 5, 21)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoriaacceso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orden',
            name='numero_orden',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Luminova.categoriainsumo'),
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
    ]
